import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { MenuProvider } from "@/lib/MenuContext";

import "./globals.css";
import Script from "next/script"; // Required for external JS files
import LenisScroll from "@/components/LenisScroll";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { ModalProvider } from "@/context/ModalContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MenuProvider>
          <ModalProvider>
            <LenisScroll />
            <NavBar />
            {children}
            <Footer />
          </ModalProvider>
        </MenuProvider>

        {/* Load Swiper and GSAP dynamically */}
        <Script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js" />
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/gsap.min.js" />
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/ScrollTrigger.min.js" />

        <Script src="/app.js" />
      </body>
    </html>
  );
}
